/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as IdopontRouteImport } from './routes/idopont'
import { Route as CsaladfaRouteImport } from './routes/csaladfa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUzenetekRouteImport } from './routes/_authenticated/uzenetek'
import { Route as AuthenticatedFiokRouteImport } from './routes/_authenticated/fiok'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUzenetekRouteImport } from './routes/_authenticated/admin/uzenetek'
import { Route as AuthenticatedAdminIdopontokRouteImport } from './routes/_authenticated/admin/idopontok'
import { Route as AuthenticatedAdminCsaladfaRouteImport } from './routes/_authenticated/admin/csaladfa'

const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const IdopontRoute = IdopontRouteImport.update({
  id: '/idopont',
  path: '/idopont',
  getParentRoute: () => rootRouteImport,
} as any)
const CsaladfaRoute = CsaladfaRouteImport.update({
  id: '/csaladfa',
  path: '/csaladfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUzenetekRoute = AuthenticatedUzenetekRouteImport.update({
  id: '/uzenetek',
  path: '/uzenetek',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiokRoute = AuthenticatedFiokRouteImport.update({
  id: '/fiok',
  path: '/fiok',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUzenetekRoute =
  AuthenticatedAdminUzenetekRouteImport.update({
    id: '/uzenetek',
    path: '/uzenetek',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdopontokRoute =
  AuthenticatedAdminIdopontokRouteImport.update({
    id: '/idopontok',
    path: '/idopontok',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCsaladfaRoute =
  AuthenticatedAdminCsaladfaRouteImport.update({
    id: '/csaladfa',
    path: '/csaladfa',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/csaladfa': typeof CsaladfaRoute
  '/idopont': typeof IdopontRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/fiok': typeof AuthenticatedFiokRoute
  '/uzenetek': typeof AuthenticatedUzenetekRoute
  '/admin/csaladfa': typeof AuthenticatedAdminCsaladfaRoute
  '/admin/idopontok': typeof AuthenticatedAdminIdopontokRoute
  '/admin/uzenetek': typeof AuthenticatedAdminUzenetekRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/csaladfa': typeof CsaladfaRoute
  '/idopont': typeof IdopontRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/fiok': typeof AuthenticatedFiokRoute
  '/uzenetek': typeof AuthenticatedUzenetekRoute
  '/admin/csaladfa': typeof AuthenticatedAdminCsaladfaRoute
  '/admin/idopontok': typeof AuthenticatedAdminIdopontokRoute
  '/admin/uzenetek': typeof AuthenticatedAdminUzenetekRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/csaladfa': typeof CsaladfaRoute
  '/idopont': typeof IdopontRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/fiok': typeof AuthenticatedFiokRoute
  '/_authenticated/uzenetek': typeof AuthenticatedUzenetekRoute
  '/_authenticated/admin/csaladfa': typeof AuthenticatedAdminCsaladfaRoute
  '/_authenticated/admin/idopontok': typeof AuthenticatedAdminIdopontokRoute
  '/_authenticated/admin/uzenetek': typeof AuthenticatedAdminUzenetekRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/csaladfa'
    | '/idopont'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
    | '/admin'
    | '/fiok'
    | '/uzenetek'
    | '/admin/csaladfa'
    | '/admin/idopontok'
    | '/admin/uzenetek'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/csaladfa'
    | '/idopont'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
    | '/fiok'
    | '/uzenetek'
    | '/admin/csaladfa'
    | '/admin/idopontok'
    | '/admin/uzenetek'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/csaladfa'
    | '/idopont'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
    | '/_authenticated/admin'
    | '/_authenticated/fiok'
    | '/_authenticated/uzenetek'
    | '/_authenticated/admin/csaladfa'
    | '/_authenticated/admin/idopontok'
    | '/_authenticated/admin/uzenetek'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CsaladfaRoute: typeof CsaladfaRoute
  IdopontRoute: typeof IdopontRoute
  KapcsolatRoute: typeof KapcsolatRoute
  RolamRoute: typeof RolamRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idopont': {
      id: '/idopont'
      path: '/idopont'
      fullPath: '/idopont'
      preLoaderRoute: typeof IdopontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csaladfa': {
      id: '/csaladfa'
      path: '/csaladfa'
      fullPath: '/csaladfa'
      preLoaderRoute: typeof CsaladfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/uzenetek': {
      id: '/_authenticated/uzenetek'
      path: '/uzenetek'
      fullPath: '/uzenetek'
      preLoaderRoute: typeof AuthenticatedUzenetekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiok': {
      id: '/_authenticated/fiok'
      path: '/fiok'
      fullPath: '/fiok'
      preLoaderRoute: typeof AuthenticatedFiokRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/uzenetek': {
      id: '/_authenticated/admin/uzenetek'
      path: '/uzenetek'
      fullPath: '/admin/uzenetek'
      preLoaderRoute: typeof AuthenticatedAdminUzenetekRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/idopontok': {
      id: '/_authenticated/admin/idopontok'
      path: '/idopontok'
      fullPath: '/admin/idopontok'
      preLoaderRoute: typeof AuthenticatedAdminIdopontokRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/csaladfa': {
      id: '/_authenticated/admin/csaladfa'
      path: '/csaladfa'
      fullPath: '/admin/csaladfa'
      preLoaderRoute: typeof AuthenticatedAdminCsaladfaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCsaladfaRoute: typeof AuthenticatedAdminCsaladfaRoute
  AuthenticatedAdminIdopontokRoute: typeof AuthenticatedAdminIdopontokRoute
  AuthenticatedAdminUzenetekRoute: typeof AuthenticatedAdminUzenetekRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCsaladfaRoute: AuthenticatedAdminCsaladfaRoute,
  AuthenticatedAdminIdopontokRoute: AuthenticatedAdminIdopontokRoute,
  AuthenticatedAdminUzenetekRoute: AuthenticatedAdminUzenetekRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFiokRoute: typeof AuthenticatedFiokRoute
  AuthenticatedUzenetekRoute: typeof AuthenticatedUzenetekRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFiokRoute: AuthenticatedFiokRoute,
  AuthenticatedUzenetekRoute: AuthenticatedUzenetekRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CsaladfaRoute: CsaladfaRoute,
  IdopontRoute: IdopontRoute,
  KapcsolatRoute: KapcsolatRoute,
  RolamRoute: RolamRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
